// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAstroSaathiProdApiKeyPlaceholder',
    appId: '1:109823471092:web:a1b2c3d4e5f6g7h8',
    messagingSenderId: '109823471092',
    projectId: 'astrosaathi-5eeba',
    authDomain: 'astrosaathi-5eeba.firebaseapp.com',
    storageBucket: 'astrosaathi-5eeba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAstroSaathiProdApiKeyPlaceholder',
    appId: '1:109823471092:android:a1b2c3d4e5f6g7h8',
    messagingSenderId: '109823471092',
    projectId: 'astrosaathi-5eeba',
    storageBucket: 'astrosaathi-5eeba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstroSaathiProdApiKeyPlaceholder',
    appId: '1:109823471092:ios:a1b2c3d4e5f6g7h8',
    messagingSenderId: '109823471092',
    projectId: 'astrosaathi-5eeba',
    storageBucket: 'astrosaathi-5eeba.appspot.com',
    iosBundleId: 'com.astrosaathi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstroSaathiProdApiKeyPlaceholder',
    appId: '1:109823471092:ios:a1b2c3d4e5f6g7h8',
    messagingSenderId: '109823471092',
    projectId: 'astrosaathi-5eeba',
    storageBucket: 'astrosaathi-5eeba.appspot.com',
    iosBundleId: 'com.astrosaathi.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAstroSaathiProdApiKeyPlaceholder',
    appId: '1:109823471092:web:a1b2c3d4e5f6g7h8',
    messagingSenderId: '109823471092',
    projectId: 'astrosaathi-5eeba',
    authDomain: 'astrosaathi-5eeba.firebaseapp.com',
    storageBucket: 'astrosaathi-5eeba.appspot.com',
  );
}
